version: "2"
checks:
  complex-logic:
    enabled: true
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
  method-count:
    enabled: false
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    enabled: true
  identical-code:
    enabled: false
  similar-code:
    enabled: false
plugins:
  pep8:
    enabled: true
  eslint:
    enabled: false
exclude_patterns:
  - "tests/**/*.py"
  - "migrations/**/*.py"
  - "setup/**/*"
  - "bin/**/*"
  - "**/node_modules/"
  - "client/dist/"
  - "**/*.pyc"
