linters:
  flake8:
    fixer: true
    config: './setup.cfg'
  py3k:
  eslint:
    config: './client/.eslintrc.js'
    fixer: true
files:
  ignore:
    - 'node_modules/*'
    - 'setup/*'
    - 'migrations/*'
    - 'webpack.config.js'
fixers:
  enable: true
