name: Javascript Code Formatting (Prettier)

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
	- uses: actions/setup-node@v1
      with:
        node-version: 12.x 
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Node Packages
      run: npm install
    - name: Run Prettier
      run: npm run prettier
    - name: Commit formatted code
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: Black
        author_email: team@redash.io
        message: "Autoformatted Javascript code with Prettier"
        path: "client"
        pattern: "*.jsx"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Commit formatted code
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: Black
        author_email: team@redash.io
        message: "Autoformatted Javascript code with Prettier"
        path: "client"
        pattern: "*.js"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

