name: Build and Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to build for'
        required: true
        type: string

env:
  ECR_REPOSITORY: 890143176237.dkr.ecr.us-east-1.amazonaws.com/adrsbl-redash
  IMAGE_TAG: ${{ inputs.version || github.ref_name }}
  IMAGE: 890143176237.dkr.ecr.us-east-1.amazonaws.com/adrsbl-redash:${{ inputs.version || github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to remote server, pull new version and restart docker
        run: |
          img=${IMAGE}
          echo "${{ secrets.A9E_REDASH_STAGING_PEM }}" > key.pem && chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@ec2-50-16-85-10.compute-1.amazonaws.com <<EOL
            cd /opt/redash
            cat docker-compose.yml
            cat docker-compose.yml.copy
          EOL
